# Frontend Service Deployment for XploreSG Local Development
# React/Vue/Angular frontend application

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  namespace: xploresg-dev
  labels:
    app.kubernetes.io/name: frontend-service
    app.kubernetes.io/component: frontend
    app.kubernetes.io/version: "1.0.0"
spec:
  replicas: 1 # Single replica for development
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend-service
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend-service
          image: xploresg/frontend:latest # Replace with your actual image
          imagePullPolicy: Always # For development; use IfNotPresent for production
          ports:
            - containerPort: 80 # Nginx serves on port 80
              name: http
          env:
            # API Backend endpoints
            - name: REACT_APP_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: api-base-url
            - name: REACT_APP_USER_SERVICE_URL
              value: "http://user-service:3001"
            # # Additional service URLs (uncomment as services are added)
            # - name: REACT_APP_BOOKING_SERVICE_URL
            #   value: "http://booking-service:3002"
            # - name: REACT_APP_NOTIFICATION_SERVICE_URL
            #   value: "http://notification-service:3003"

            # Environment configuration
            - name: NODE_ENV
              value: "development"

          # Health checks
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 3

          # Resource limits for local development
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"

---
# Frontend Service ClusterIP Service
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: xploresg-dev
  labels:
    app.kubernetes.io/name: frontend-service
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: frontend-service
